---

resources:

- name: concourse-git
  type: git
  source:
    uri: https://github.com/joonkwonyahoo/concoursepipe.git
    branch: master
    username: {{username}}
    password: {{password}}


jobs:

- name: simplejob
  
  plan:
  - aggregate:
    - get: concourse-git
      trigger: true

  - task: simpletask
    file: concourse-git/tasks/example.yml
    # config:
    #   platform: linux
    #   image_resource:
    #     type: docker-image
    #     source:
    #       repository: 10.113.8.12:5000/ubuntu
    #       insecure_registries: ["10.113.8.12:5000"]
    #   inputs:
    #     - name: concourse-git
    #   run:
    #     path: echo
    #     args: ["Hello world $SAMPLE_PARAM"]
    #   params:
    #     SAMPLE_PARAM:  concourse
